services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/.Xauthority
